ecommerce/ecommerce/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^orders/', include('orders.urls', namespace="orders")),
    url(r'^admin/', include(admin.site.urls)),
]

ecommerce/orders/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>([0-9]+|[A-Z]+|\-)+)/$', views.DetailView.as_view(),
        name='detail'),
    url(r'^new/$', views.order_new, name='order_new'),
    url(r'^(?P<pk>([0-9]+|[A-Z]+|\-)+)/remove/$', views.order_remove,
        name='order_remove'),
    url(r'^(?P<pk>([0-9]+|[A-Z]+|\-)+)/edit/$', views.order_edit,
        name='order_edit'),
]

ecommerce/orders/models.py
from django.db import models

class Order(models.Model):
    marketplace = models.CharField(max_length=100)
    order_purchase_date = models.DateField('purchase date')
    order_amount = models.FloatField()
    order_currency = models.CharField(max_length=3)
    order_id = models.CharField(max_length=19, primary_key=True)

    def __unicode__(self): # __str__ on Python 3
        return self.order_id

ecommerce/orders/forms.py
from django import forms

from .models import Order

class OrderForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = ('marketplace', 'order_purchase_date',
                'order_amount', 'order_currency', 'order_id',)

ecommerce/orders/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.db.models import Q

from rest_framework import viewsets
from rest_framework.response import Response
from rest_framework_xml.parsers import XMLParser
from rest_framework_xml.renderers import XMLRenderer

from .serializers import OrderSerializer
from .models import Order
from .forms import OrderForm


class IndexView(generic.ListView):
    """
    A simple view to list all orders, or filter by attribute.
    """
    template_name = 'orders/index.html'
    context_object_name = 'latest_order_list'

    def get_queryset(self):
        search = self.request.GET.get('search')
        if search :
            return Order.objects.filter(
                Q(marketplace__contains = search)
                | Q(order_id__contains = search)
                | Q(order_amount__contains = search)
                | Q(order_currency__contains = search)
                | Q(order_purchase_date__contains = search)
                )
        else :
            return Order.objects.all()


class DetailView(generic.DetailView):
    """
    A simple view to see details of an order.
    """
    model = Order
    template_name = 'orders/detail.html'


class OrderViewSet(viewsets.ModelViewSet):
    """
    A viewset for viewing and editing order instances, with the rest Framework.
    """
    serializer_class = OrderSerializer
    queryset = Order.objects.all()
    parser_classes = (XMLParser,)
    renderer_classes = (XMLRenderer,)


def order_new(request):
    """
    A simple view to add a new order.
    """
    if request.method == "POST":
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save()
            return redirect('orders:detail', pk=order.order_id)
    else:
        form = OrderForm()
    return render(request, 'orders/order_edit.html', {'form': form})


def order_remove(request, pk):
    """
    A simple view to remove an order.
    """
    order = get_object_or_404(Order, pk=pk)
    order.delete()
    return redirect('orders:index')


def order_edit(request, pk):
    """
    A simple view to edit an order.
    """
    order = get_object_or_404(Order, pk=pk)
    if request.method == "POST":
        form = OrderForm(request.POST, instance=order)
        if form.is_valid():
            order = form.save()
            return redirect('orders:detail', pk=order.order_id)
    else:
        form = OrderForm(instance=order)
    return render(request, 'orders/order_edit.html', {'form': form})

ecommerce/orders/templates/orders/detail.html
{% extends "orders/skeleton.html" %}

{% block content %}

<div class="container">

    <h1>Order: {{ order.order_id }}</h1>
    <ul>
        <li>Marketplace: {{ order.marketplace }}</li>
        <li>Purchase date: {{ order.order_purchase_date }}</li>
        <li>Amount: {{ order.order_amount }} {{order.order_currency}}</li>
    </ul>
    <a class="btn btn-danger" href="{% url 'orders:order_remove' pk=order.pk %}">
        <span class="glyphicon glyphicon-remove"> Remove</span>
    </a>

    <a class="btn btn-warning" href="{% url 'orders:order_edit' pk=order.pk %}">
        <span class="glyphicon glyphicon-pencil">Edit</span>
    </a>

    <a class="btn btn-default" href="{% url 'orders:index' %}">Return</a>

</div>

{% endblock %}

ecommerce/orders/templates/orders/index.html
{% extends "orders/skeleton.html" %}

{% block content %}

<div class="container">

    <li class="line">
        <h2>Orders</h2>
    </li>
    <li class="line">
        <a class="save btn btn-success" href="{% url 'orders:order_new' %}" class="top-menu">
            <span class="glyphicon glyphicon-plus"></span>
        </a>
    </li>


    {% if latest_order_list %}
        <ul>
        {% for order in latest_order_list %}
            <li>
                <a href="{% url 'orders:detail' order.order_id %}">Order: {{ order.order_id }}</a>
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No orders are available.</p>
    {% endif %}

    <!-- Search form-->
    <h4>Search a specific order</h4>
    <p>Ex: by place (amazone), by price, by date</p>
    <form action="{% url 'orders:index' %}" method="GET">
        <input type="search" name="search"/>
        <input type="submit" value="go !"/>
    </form>
</div>

{% endblock %}

ecommerce/orders/templates/orders/order_edit.html
{% extends "orders/skeleton.html" %}

{% block content %}

<div class="container">

    <h2>New Order</h2>
    <form method="POST" class="order-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-success">Save</button>
        <a class="btn btn-default" href="{% url 'orders:index' %}">Return</a>
    </form>
    <h4>After validation, you will be redirected to the details page of your order.</h4>

</div>

{% endblock %}

ecommerce/orders/templates/orders/skeleton.html
<!DOCTYPE HTML>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>App - ecommerce</title> 

        {% load staticfiles %}
        <link rel="stylesheet" type="text/css" href="{% static 'orders/style.css' %}" />
         <!-- Bootstrap -->
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    </head>
    <body>
        <div id="container" >
            <div id="header">
                <div class="container">
                    <h1>TApp - ecommerce : app orders</h1>
                </div>
            </div>
            <div id="content">
                {% block content %}
                {% endblock %}
            </div>
            <div id="footer">
                <div class="container">
                    <p>Author: Marie-Charlotte Daureu - Django 1.8.4 - Python 2.7.6</p>
                </div>
            </div>
        </div>

        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

    </body>
</html>